# Numpy:

In [ ]:
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.
- NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering.
 The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures,python.

# Installation of Numpy:

In [4]:
!pip install Numpy

# How to import NumPy:

In [ ]:
- Once NumPy is installed, import it in your applications by adding the import keyword:

In [2]:
#importing numpy
import numpy as np

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Initial Placeholders:

In [13]:
# Creatr an array of zeros
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
#create an arrray of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#create a 3D array
e=np.full((2,2,2),7)
print(e)
print("No of dimension:",e.ndim)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
No of dimension: 3


In [19]:
# create a 2*2 identity matrix
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# to find no of elements in array 
arr=np.array([[1,2,3,4],[5,6,7,8],[5,7,7,8]])
print(arr.shape)

(3, 4)


# access Array elements:

In [ ]:
- We can access an array element by referring to its index number
- The indexes in Numpy arrays start with 0 i.e, the first element has index 0.

In [26]:
arr=np.array([1,2,3,4])
print(arr[2])

3


In [28]:
import numpy as np
#Adding two Index position
arr=np.array([1,2,3,4])
print(arr[2]+arr[3]-arr[0])

6


In [30]:
# Access 2-D Arrays 
# access the element on the first row,second column:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[6,7,5,9,10],[6,7,8,9,1]])
print('2nd element on 1st row:',arr[1,3])

2nd element on 1st row: 9


In [32]:
#Access 3-D Arrays
arr=np.array([[[1,2,3],[4,5,6]],[[1,22,3],[24,5,6]],[[1,32,32],[4,2,6]],[[7,8,9],[10,11,12]]])
#Acess by index
print(arr[3,1,0])

10


# Data Types in Numpy:

In [ ]:
- Numpy has some extra data types and refer to data types with one character like i for integers, u for unsigned integers etc.
- Below is a list of all datatypes in Numpy and the characters used to represent them.
i-integer
b-boolean
u-unsigned integer
f-float
c-complex float
M-date time
o-object
s-string

In [41]:
# String
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [43]:
# Integer
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [45]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Reshaping arrays:

In [ ]:
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension..

In [48]:
#convert the following 1-D array with 12 elements into 2-d array.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr.size)
print("+++++++++++++")
newarr=arr.reshape(1,13)
print(newarr)

13
+++++++++++++
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]]


# Sorting Arrays:

In [ ]:
- sorting means putting elements in an ordered sequence.
- the Numpy ndarray object has a function called sort(), that will sort a specified array.

In [51]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


# Slicing Arrays:

In [ ]:
- slicing in python mmeans taking elements form one given index to another given index.
- We pass slice instead of index like this:[start:end].
- We can also define the step,like this:[start:end:step]
- If we don't pass start its considered 0.
- If we don't pass end its considered 1

In [54]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [60]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]
